# Image base légère pour dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Pas besoin de copier tout le code (live via volumes)

EXPOSE 3000

# Commande spéciale pour dev avec hot reload
CMD ["npm", "run", "dev"]
