
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=ton_uri_mongo_atlas
      - JWT_SECRET=ton_jwt_secret
    restart: unless-stopped

