name: "Backend Deploy"

on:
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: test
      JWT_SECRET: test-jwt-secret-key-for-testing-purposes-only-minimum-32-chars-long
      CI: true
      API_BASE_URL: http://localhost:5001
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      
      - name: Build application
        working-directory: backend
        run: npm run build
      
      - name: Run tests
        working-directory: backend
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Verify Heroku CLI installation
        run: |
          which heroku || echo "Heroku CLI not in PATH"
          ls -la $HOME/.local/bin/ || echo "No .local/bin directory"
          # Add Heroku CLI to PATH manually
          export PATH="$HOME/.local/bin:$PATH"
          heroku --version
          
      - name: Login to Heroku
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
          heroku apps --json
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
      - name: Set Heroku remote
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cd backend
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
      - name: Deploy to Heroku
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cd backend
          # Create a new git repo for deployment
          git init
          git add .
          git commit -m "Deploy to Heroku"
          git push heroku HEAD:main --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 