name: "Backend Deploy"

on:
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  build-and-test:
    name: "Build & Test Backend"
    runs-on: ubuntu-latest
    

    defaults:
      run:
        working-directory: ./backend

    env:
      NODE_ENV: test
      JWT_SECRET: test-jwt-secret-key-for-testing-purposes-only-minimum-32-chars-long
      CI: true
      API_BASE_URL: http://localhost:5001
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Run tests
        run: npm test

  deploy:
    name: "Deploy to Heroku"
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
        env:
          NODE_ENV: production