name: "Backend Deploy"

on:
  push:
    branches: [main]
    paths: ["backend/**"]

jobs:
  build-and-test:
    name: "Build & Test Backend"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    env:
      NODE_ENV: test
      JWT_SECRET: test-jwt-secret-key-for-testing-purposes-only-minimum-32-chars-long
      CI: true
      API_BASE_URL: http://localhost:5001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    name: "Deploy to Heroku"
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Debug Heroku Secrets
        run: |
          echo "Vérification des secrets pour Heroku..."
          if [ -z "${{ secrets.HEROKU_APP_NAME }}" ]; then
            echo "::error::Le secret HEROKU_APP_NAME est vide ou non défini !"
            exit 1
          else
            echo "HEROKU_APP_NAME est défini."
          fi

          if [ -z "${{ secrets.HEROKU_API_KEY }}" ]; then
            echo "::error::Le secret HEROKU_API_KEY est vide ou non défini !"
            exit 1
          else
            echo "HEROKU_API_KEY est défini."
          fi

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
          dontautocreate: true
        env:
          NODE_ENV: production
