name: "Backend CI/CD (Alternative)"

on:
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Add environment variables for tests
    env:
      NODE_ENV: test
      JWT_SECRET: test-jwt-secret-key-for-testing-purposes-only-minimum-32-chars-long
      CI: true
      API_BASE_URL: http://localhost:5001
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      
      - name: Build application
        working-directory: backend
        run: npm run build
      
      - name: Run tests with CI configuration
        working-directory: backend
        run: npm test
        env:
          NODE_OPTIONS: '--max-old-space-size=4096 --unhandled-rejections=strict'

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Heroku
        uses: heroku/deploy-via-git@v1
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          app-name: ${{ secrets.HEROKU_APP_NAME }}
          email: ${{ secrets.HEROKU_EMAIL }}
          app-directory: backend 